-- E-VoteSys - Creacion de tablas (sin PK/FK/CHECK, ver 02_constraints.sql)
-- Orden: sin dependencias -> CONTRACT -> ELECTION -> (CANDIDATE/ELECTION_SDG/VOTER_ELECTION_STATUS/VOTE)

CREATE TABLE CURRENCY (
    ID_CURRENCY INTEGER NOT NULL,
    NAME        VARCHAR2(50),
    SYMBOL      VARCHAR2(5)
);

CREATE TABLE SDG (
    ID_SDG      INTEGER NOT NULL,
    DESCRIPTION VARCHAR2(300)
);

CREATE TABLE VOTER (
    ID_VOTER    INTEGER NOT NULL,
    DOCUMENT_ID VARCHAR2(20),
    FULL_NAME   VARCHAR2(150),
    EMAIL       VARCHAR2(150)
);

CREATE TABLE CONTRACT (
    ID_CONTRACT           INTEGER NOT NULL,
    CLIENT_NAME           VARCHAR2(150),
    TOTAL_AMOUNT          NUMBER(12,2),
    DATE_SIGNED           DATE,
    CURRENCY_ID_CURRENCY  INTEGER NOT NULL
);

CREATE TABLE ELECTION (
    ID_ELECTION           INTEGER NOT NULL,
    TITLE                 VARCHAR2(200),
    START_DATE            DATE,
    END_DATE              DATE,
    STATUS                VARCHAR2(20),
    CONTRACT_ID_CONTRACT  INTEGER NOT NULL
);

CREATE TABLE CANDIDATE (
    ID_CANDIDATE            INTEGER NOT NULL,
    NAME                    VARCHAR2(150),
    PARTY_NAME              VARCHAR2(150),
    PHOTO_URL               VARCHAR2(500),
    ELECTION_ID_ELECTION    INTEGER NOT NULL
);

CREATE TABLE ELECTION_SDG (
    ELECTION_ID_ELECTION INTEGER NOT NULL,
    SDG_ID_SDG           INTEGER NOT NULL
);

CREATE TABLE VOTER_ELECTION_STATUS (
    VOTER_ID_VOTER        INTEGER NOT NULL,
    ELECTION_ID_ELECTION  INTEGER NOT NULL,
    HAS_VOTED             CHAR(1) DEFAULT 'N',
    VOTE_DATE             DATE
);

CREATE TABLE VOTE (
    ID_VOTE                   INTEGER NOT NULL,
    VOTE_TIMESTAMP            TIMESTAMP,
    HASH_CODE                 VARCHAR2(256),
    ELECTION_ID_ELECTION      INTEGER NOT NULL,
    CANDIDATE_ID_CANDIDATE    INTEGER NOT NULL
);
