-- E-VoteSys - Restricciones: PRIMARY KEY, FOREIGN KEY, CHECK
-- Nombres de constraint tal como en el diccionario de datos (README seccion 4.2)

-- CURRENCY
ALTER TABLE CURRENCY ADD CONSTRAINT CURRENCY_PK PRIMARY KEY (ID_CURRENCY);

-- SDG
ALTER TABLE SDG ADD CONSTRAINT SDG_PK PRIMARY KEY (ID_SDG);

-- VOTER
ALTER TABLE VOTER ADD CONSTRAINT VOTER_PK PRIMARY KEY (ID_VOTER);

-- CONTRACT
ALTER TABLE CONTRACT ADD CONSTRAINT CONTRACT_PK PRIMARY KEY (ID_CONTRACT);
ALTER TABLE CONTRACT ADD CONSTRAINT CONTRACT_CURRENCY_FK
    FOREIGN KEY (CURRENCY_ID_CURRENCY) REFERENCES CURRENCY (ID_CURRENCY);

-- ELECTION
ALTER TABLE ELECTION ADD CONSTRAINT ELECTION_PK PRIMARY KEY (ID_ELECTION);
ALTER TABLE ELECTION ADD CONSTRAINT ELECTION_CONTRACT_FK
    FOREIGN KEY (CONTRACT_ID_CONTRACT) REFERENCES CONTRACT (ID_CONTRACT);
-- RN04: END_DATE debe ser estrictamente posterior a START_DATE
ALTER TABLE ELECTION ADD CONSTRAINT ELECTION_DATES_CHK
    CHECK (END_DATE > START_DATE);

-- CANDIDATE
ALTER TABLE CANDIDATE ADD CONSTRAINT CANDIDATE_PK PRIMARY KEY (ID_CANDIDATE);
ALTER TABLE CANDIDATE ADD CONSTRAINT CANDIDATE_ELECTION_FK
    FOREIGN KEY (ELECTION_ID_ELECTION) REFERENCES ELECTION (ID_ELECTION);

-- ELECTION_SDG
ALTER TABLE ELECTION_SDG ADD CONSTRAINT Relation_4_PK
    PRIMARY KEY (ELECTION_ID_ELECTION, SDG_ID_SDG);
ALTER TABLE ELECTION_SDG ADD CONSTRAINT Relation_4_ELECTION_FK
    FOREIGN KEY (ELECTION_ID_ELECTION) REFERENCES ELECTION (ID_ELECTION);
ALTER TABLE ELECTION_SDG ADD CONSTRAINT Relation_4_SDG_FK
    FOREIGN KEY (SDG_ID_SDG) REFERENCES SDG (ID_SDG);

-- VOTER_ELECTION_STATUS
ALTER TABLE VOTER_ELECTION_STATUS ADD CONSTRAINT VOTER_ELECTION_STATUS_PK
    PRIMARY KEY (VOTER_ID_VOTER, ELECTION_ID_ELECTION);
ALTER TABLE VOTER_ELECTION_STATUS ADD CONSTRAINT VOTER_ELECTION_STATUS_VOTER_FK
    FOREIGN KEY (VOTER_ID_VOTER) REFERENCES VOTER (ID_VOTER);
ALTER TABLE VOTER_ELECTION_STATUS ADD CONSTRAINT VOTER_ELECTION_STATUS_ELECTION_FK
    FOREIGN KEY (ELECTION_ID_ELECTION) REFERENCES ELECTION (ID_ELECTION);
ALTER TABLE VOTER_ELECTION_STATUS ADD CONSTRAINT VOTER_ELECTION_STATUS_HASVOTED_CHK
    CHECK (HAS_VOTED IN ('S', 'N'));

-- VOTE (RN03: inmutabilidad se aplica via privilegios/trigger, ver 04_plsql y 05_security)
ALTER TABLE VOTE ADD CONSTRAINT VOTE_PK PRIMARY KEY (ID_VOTE);
ALTER TABLE VOTE ADD CONSTRAINT VOTE_ELECTION_FK
    FOREIGN KEY (ELECTION_ID_ELECTION) REFERENCES ELECTION (ID_ELECTION);
ALTER TABLE VOTE ADD CONSTRAINT VOTE_CANDIDATE_FK
    FOREIGN KEY (CANDIDATE_ID_CANDIDATE) REFERENCES CANDIDATE (ID_CANDIDATE);
