-- E-VoteSys - Secuencias para IDs autonumericos + indices de soporte sobre FKs
-- (Oracle no indexa automaticamente columnas FK, solo la PK)

CREATE SEQUENCE SEQ_CURRENCY  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CONTRACT  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ELECTION  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CANDIDATE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SDG       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VOTER     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VOTE      START WITH 1 INCREMENT BY 1 NOCACHE;

-- Indices sobre columnas FK (la columna lider de cada PK compuesta ya queda indexada)
CREATE INDEX IDX_CONTRACT_CURRENCY  ON CONTRACT (CURRENCY_ID_CURRENCY);
CREATE INDEX IDX_ELECTION_CONTRACT  ON ELECTION (CONTRACT_ID_CONTRACT);
CREATE INDEX IDX_CANDIDATE_ELECTION ON CANDIDATE (ELECTION_ID_ELECTION);
CREATE INDEX IDX_ELECTIONSDG_SDG    ON ELECTION_SDG (SDG_ID_SDG);
CREATE INDEX IDX_VES_ELECTION       ON VOTER_ELECTION_STATUS (ELECTION_ID_ELECTION);
CREATE INDEX IDX_VOTE_ELECTION      ON VOTE (ELECTION_ID_ELECTION);
CREATE INDEX IDX_VOTE_CANDIDATE     ON VOTE (CANDIDATE_ID_CANDIDATE);
